package io.imiocode.team;

import io.imiocode.team.backend.*;
import io.imiocode.team.coordinator.*;
import io.imiocode.team.model.*;
import io.imiocode.tool.ToolSelection;
import org.junit.jupiter.api.Test;
import java.nio.file.Path;
import java.nio.file.Files;
import java.time.Duration;
import java.util.*;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.concurrent.atomic.AtomicBoolean;
import static org.junit.jupiter.api.Assertions.*;

class BackendCoordinatorTest {
    @Test void autoUsesTmuxOnlyInsideTmuxAndExplicitFailureDoesNotFallback(){FakeBackend tmux=new FakeBackend(TeamBackend.TMUX,true),in=new FakeBackend(TeamBackend.IN_PROCESS,true);BackendSelector inside=new BackendSelector(List.of(tmux,in),Map.of("TMUX","/tmp/tmux"),"Linux",Duration.ofMillis(10));assertEquals(TeamBackend.TMUX,inside.select(TeamBackend.AUTO).backend().kind());BackendSelector outside=new BackendSelector(List.of(tmux,in),Map.of(),"Windows",Duration.ofMillis(10));assertEquals(TeamBackend.IN_PROCESS,outside.select(TeamBackend.AUTO).backend().kind());tmux.available=false;assertThrows(TeamException.class,()->inside.select(TeamBackend.TMUX));}
    @Test void coordinatorRequiresDoubleLockAndStrictStageOrder(){TeamPrincipal lead=new TeamPrincipal("demo","lead",TeamRole.LEAD);assertThrows(TeamException.class,()->new CoordinatorModeController(true,Map.of()).enter(lead,ToolSelection.allEnabled()));CoordinatorModeController c=new CoordinatorModeController(true,Map.of("IMIO_COORDINATOR_MODE","true"));assertEquals(CoordinatorStage.RESEARCH,c.enter(lead,ToolSelection.allEnabled()).stage());assertFalse(c.snapshot().selection().allows("bash"));assertThrows(TeamException.class,()->c.advance(CoordinatorStage.RESEARCH,CoordinatorStage.IMPLEMENTATION));c.advance(CoordinatorStage.RESEARCH,CoordinatorStage.SYNTHESIS);c.advance(CoordinatorStage.SYNTHESIS,CoordinatorStage.IMPLEMENTATION);c.advance(CoordinatorStage.IMPLEMENTATION,CoordinatorStage.VERIFICATION);assertTrue(c.exit().unrestricted());}
    @Test void coordinatorAllowsReadOnlyConvergenceButStillDeniesDirectWork(){CoordinatorModeController c=new CoordinatorModeController(true,Map.of("IMIO_COORDINATOR_MODE","true"));c.enter(new TeamPrincipal("demo","lead",TeamRole.LEAD),ToolSelection.allEnabled());assertTrue(c.snapshot().selection().allows("TeamConverge"));assertFalse(c.snapshot().selection().allows("read_file"));assertFalse(c.snapshot().selection().allows("TeamDelete"));}
    @Test void tmuxUsesArgumentArraysAndWakeContainsNoMessageBody(){List<List<String>> commands=new CopyOnWriteArrayList<>();ProcessExecutor executor=(cwd,command,timeout)->{commands.add(List.copyOf(command));if(command.contains("split-window"))return new ProcessResult(0,"%7");return new ProcessResult(0,"ok");};TmuxBackend backend=new TmuxBackend(executor,Path.of("."),Map.of("TMUX","/tmp/tmux"));var request=new TeammateLaunchRequest("demo","worker",Path.of("."),Path.of("."),List.of("java","-jar","imio.jar","--team-member","demo","worker"),()->{});BackendHandle handle=backend.start(request);backend.wake(handle);String all=commands.toString();assertTrue(all.contains("split-window"));assertTrue(all.contains("--team-member"));assertTrue(all.contains("IMIO_MAILBOX_WAKE"));assertFalse(all.contains("secret-body"));}
    @Test void tmuxProbeFailsClosedOutsideCurrentSessionEvenIfAnotherServerResponds(){ProcessExecutor executor=(cwd,command,timeout)->new ProcessResult(0,"$9");assertFalse(new TmuxBackend(executor,Path.of("."),Map.of()).probe(Duration.ofMillis(10)).available());}
    @Test void itermIsUnavailableOffMac(){ITerm2Backend backend=new ITerm2Backend((cwd,command,timeout)->new ProcessResult(0,"ok"),Path.of("."),"Windows 11");assertFalse(backend.probe(Duration.ofMillis(10)).available());}
    @Test void itermCreatesSplitPaneWithPrivateLauncherAndCleansIt()throws Exception{List<List<String>> commands=new ArrayList<>();ProcessExecutor executor=(cwd,command,timeout)->{commands.add(List.copyOf(command));if(command.getFirst().equals("osascript")&&command.toString().contains("split vertically"))return new ProcessResult(0,"session-7");return new ProcessResult(0,"ok");};ITerm2Backend backend=new ITerm2Backend(executor,Path.of("."),"Mac OS X");var request=new TeammateLaunchRequest("demo","worker",Path.of("."),Path.of("."),List.of("java","-jar","imio.jar","--team-member","demo","worker"),()->{});BackendHandle handle=backend.start(request);List<String> split=commands.stream().filter(command->command.getFirst().equals("osascript")&&command.toString().contains("split vertically")).findFirst().orElseThrow();Path script=launcherPath(split);String body=Files.readString(script);assertTrue(body.contains("--team-member"));assertFalse(body.contains("secret-prompt"));backend.stop(handle,Duration.ofMillis(100));assertFalse(Files.exists(script));}
    @Test void failedTmuxStopKeepsOwnedHandleForRetry(){AtomicBoolean fail=new AtomicBoolean(true);ProcessExecutor executor=(cwd,command,timeout)->{if(command.contains("split-window"))return new ProcessResult(0,"%9");if(command.contains("kill-pane"))return new ProcessResult(fail.get()?1:0,"");if(command.contains("display-message"))return new ProcessResult(0,"%9");return new ProcessResult(0,"ok");};TmuxBackend backend=new TmuxBackend(executor,Path.of("."),Map.of("TMUX","/tmp/tmux"));BackendHandle handle=backend.start(new TeammateLaunchRequest("demo","worker",Path.of("."),Path.of("."),List.of("java","member"),()->{}));assertThrows(TeamException.class,()->backend.stop(handle,Duration.ofMillis(100)));backend.wake(handle);fail.set(false);assertDoesNotThrow(()->backend.stop(handle,Duration.ofMillis(100)));}
    @Test void failedItermStopPreservesLauncherAndHandle()throws Exception{AtomicBoolean failKill=new AtomicBoolean(true);List<List<String>> commands=new ArrayList<>();ProcessExecutor executor=(cwd,command,timeout)->{commands.add(List.copyOf(command));if(command.getFirst().equals("osascript")&&command.toString().contains("split vertically"))return new ProcessResult(0,"session-8");if(command.size()>1&&command.getFirst().equals("kill")&&command.get(1).equals("-TERM"))return new ProcessResult(failKill.get()?1:0,"");if(command.size()>1&&command.getFirst().equals("kill")&&command.get(1).equals("-0"))return new ProcessResult(0,"");return new ProcessResult(0,"ok");};ITerm2Backend backend=new ITerm2Backend(executor,Path.of("."),"Mac OS X");BackendHandle handle=backend.start(new TeammateLaunchRequest("demo","worker",Path.of("."),Path.of("."),List.of("java","member"),()->{}));List<String> split=commands.stream().filter(command->command.getFirst().equals("osascript")&&command.toString().contains("split vertically")).findFirst().orElseThrow();Path script=launcherPath(split);Files.writeString(script.resolveSibling("member.pid"),"12345");assertThrows(TeamException.class,()->backend.stop(handle,Duration.ofMillis(100)));assertTrue(Files.exists(script));failKill.set(false);backend.stop(handle,Duration.ofMillis(100));assertFalse(Files.exists(script));}
    @Test void veryShortInProcessTaskDoesNotLeaveStaleHandle()throws Exception{InProcessBackend backend=new InProcessBackend();BackendHandle handle=backend.start(new TeammateLaunchRequest("demo","worker",Path.of("."),Path.of("."),List.of(),()->{}));Thread.sleep(100);assertThrows(TeamException.class,()->backend.wake(handle));backend.close();}
    private static Path launcherPath(List<String> command){String line=command.stream().filter(value->value.contains("member.command")).findFirst().orElseThrow();int shell=line.indexOf("/bin/sh ");int begin=line.indexOf('\'',shell);int end=line.indexOf('\'',begin+1);if(shell<0||begin<0||end<0)throw new AssertionError("未找到受控启动器: "+line);return Path.of(line.substring(begin+1,end).replace("\\\\","\\"));}
    private static final class FakeBackend implements TeammateBackend {private final TeamBackend kind;private boolean available;FakeBackend(TeamBackend kind,boolean available){this.kind=kind;this.available=available;}public TeamBackend kind(){return kind;}public BackendAvailability probe(Duration t){return available?BackendAvailability.yes():BackendAvailability.no("no");}public BackendHandle start(TeammateLaunchRequest r){return new BackendHandle(kind,"handle");}public void wake(BackendHandle h){}public void stop(BackendHandle h,Duration t){}}
}
