package io.imiocode.team.backend;

import io.imiocode.team.TeamException;
import io.imiocode.team.model.TeamBackend;
import java.nio.file.Path;
import java.time.Duration;
import java.util.*;

/** macOS iTerm2 后端：用受控 AppleScript 创建 pane，pane 内私有启动器运行独立 JVM。 */
public final class ITerm2Backend implements TeammateBackend {
    private final ProcessExecutor processes;private final Path cwd;private final String os;private final Map<String,ManagedLaunch> handles=new java.util.concurrent.ConcurrentHashMap<>();
    public ITerm2Backend(ProcessExecutor processes,Path cwd,String os){this.processes=processes;this.cwd=cwd;this.os=os==null?"":os.toLowerCase(Locale.ROOT);}
    @Override public TeamBackend kind(){return TeamBackend.ITERM2;}
    @Override public BackendAvailability probe(Duration timeout){if(!os.contains("mac"))return BackendAvailability.no("仅支持 macOS");ProcessResult r=processes.run(cwd,List.of("open","-Ra","iTerm"),timeout);return r.success()?BackendAvailability.yes():BackendAvailability.no("iTerm2 不可用");}
    @Override public BackendHandle start(TeammateLaunchRequest request){if(!probe(Duration.ofSeconds(2)).available())throw new TeamException("iTerm2 不可用");if(request.command().isEmpty())throw new TeamException("iTerm2 成员进程命令为空");ManagedLaunch files=createLauncher(request);String launchCommand="/bin/sh "+quote(files.script().toString());List<String> script=List.of("tell application \"iTerm2\"","if (count of windows) is 0 then","set targetWindow to (create window with default profile command \""+appleScript(launchCommand)+"\")","set newSession to current session of targetWindow","else","tell current session of current window","set newSession to (split vertically with same profile command \""+appleScript(launchCommand)+"\")","end tell","end if","return unique ID of newSession","end tell");ProcessResult result=runAppleScript(script,Duration.ofSeconds(10));if(!result.success()||result.output().isBlank()){cleanup(files);throw new TeamException("iTerm2 pane 启动失败");}String sessionId=result.output().lines().findFirst().orElseThrow().trim();if(sessionId.length()>256||sessionId.contains("\n")||sessionId.contains("\r")){cleanup(files);throw new TeamException("iTerm2 session 句柄无效");}ManagedLaunch launch=new ManagedLaunch(files.directory(),files.script(),files.pidFile(),sessionId);handles.put(sessionId,launch);return new BackendHandle(kind(),sessionId);}
    @Override public void wake(BackendHandle handle){require(handle);}
    @Override public void stop(BackendHandle handle,Duration timeout){String id=require(handle);ManagedLaunch launch=handles.get(id);try{if(java.nio.file.Files.isRegularFile(launch.pidFile())){String pid=java.nio.file.Files.readString(launch.pidFile()).trim();if(!pid.matches("[1-9][0-9]{0,18}"))throw new TeamException("iTerm2 成员 PID 无效");ProcessResult stopped=processes.run(cwd,List.of("kill","-TERM",pid),timeout);if(!stopped.success()){ProcessResult alive=processes.run(cwd,List.of("kill","-0",pid),Duration.ofSeconds(2));if(alive.success())throw new TeamException("iTerm2 成员进程停止失败，句柄已保留: "+id);}}ProcessResult closed=runAppleScript(List.of("tell application \"iTerm2\"","repeat with aWindow in windows","repeat with aTab in tabs of aWindow","repeat with aSession in sessions of aTab","if unique ID of aSession is \""+appleScript(launch.sessionId())+"\" then","tell aSession to close","return \"closed\"","end if","end repeat","end repeat","end repeat","return \"absent\"","end tell"),timeout);if(!closed.success())throw new TeamException("iTerm2 pane 关闭失败，句柄已保留: "+id);}catch(java.io.IOException e){throw new TeamException("无法停止 iTerm2 成员进程",e);}handles.remove(id);cleanup(launch);}
    private String require(BackendHandle h){if(h.backend()!=kind()||!handles.containsKey(h.value()))throw new TeamException("iTerm2 句柄不属于 ImioCode");return h.value();}
    @Override public void close(){for(String id:new ArrayList<>(handles.keySet()))try{stop(new BackendHandle(kind(),id),Duration.ofSeconds(2));}catch(RuntimeException ignored){}}
    private ManagedLaunch createLauncher(TeammateLaunchRequest request){try{Path directory=java.nio.file.Files.createTempDirectory("imiocode-iterm2-");Path pid=directory.resolve("member.pid"),script=directory.resolve("member.command");String command=request.command().stream().map(ITerm2Backend::quote).collect(java.util.stream.Collectors.joining(" "));String body="#!/bin/sh\nprintf '%s\\n' \"$$\" > "+quote(pid.toString())+"\ncd "+quote(request.worktree().toString())+" || exit 126\nexec "+command+"\n";java.nio.file.Files.writeString(script,body,java.nio.charset.StandardCharsets.UTF_8,java.nio.file.StandardOpenOption.CREATE_NEW);try{java.nio.file.Files.setPosixFilePermissions(script,java.nio.file.attribute.PosixFilePermissions.fromString("rwx------"));}catch(UnsupportedOperationException ignored){}return new ManagedLaunch(directory,script,pid,"");}catch(java.io.IOException e){throw new TeamException("无法创建 iTerm2 成员启动器",e);}}
    private ProcessResult runAppleScript(List<String> lines,Duration timeout){List<String> command=new ArrayList<>();command.add("osascript");for(String line:lines){command.add("-e");command.add(line);}return processes.run(cwd,command,timeout);}
    private static String quote(String value){return "'"+value.replace("'","'\"'\"'")+"'";}
    private static String appleScript(String value){return value.replace("\\","\\\\").replace("\"","\\\"");}
    private static void cleanup(ManagedLaunch launch){try{java.nio.file.Files.deleteIfExists(launch.pidFile());java.nio.file.Files.deleteIfExists(launch.script());java.nio.file.Files.deleteIfExists(launch.directory());}catch(java.io.IOException ignored){}}
    private record ManagedLaunch(Path directory,Path script,Path pidFile,String sessionId){}
}
