package io.imiocode.team.mailbox;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import io.imiocode.team.TeamException;
import io.imiocode.team.persistence.JsonlLog;
import io.imiocode.team.persistence.TeamPaths;
import io.imiocode.team.persistence.CrossProcessFileLock;
import io.imiocode.tool.SecretRedactor;
import java.time.*;
import java.util.*;

/** 每位成员独立文件的持久 Mailbox；ACK 记录保证消费幂等。 */
public final class MailboxStore {
    private final TeamPaths paths;private final JsonlLog log;private final ObjectMapper mapper=new ObjectMapper();private final SecretRedactor redactor;private final int maxChars,maxMessages;private final Clock clock;
    public MailboxStore(TeamPaths paths,SecretRedactor redactor,int maxChars,int maxMessages,int maxBytes){this(paths,redactor,maxChars,maxMessages,maxBytes,Clock.systemUTC());}
    MailboxStore(TeamPaths paths,SecretRedactor redactor,int maxChars,int maxMessages,int maxBytes,Clock clock){this.paths=Objects.requireNonNull(paths);this.redactor=Objects.requireNonNull(redactor);this.maxChars=maxChars;this.maxMessages=maxMessages;this.log=new JsonlLog(maxBytes);this.clock=clock;}
    public synchronized MailboxMessage send(String team,String sender,String recipient,MailboxMessageType type,String summary,String body,String taskId){paths.requireSlug(team,"team");paths.requireSlug(sender,"sender");paths.requireSlug(recipient,"recipient");String safeSummary=redactor.redact(Objects.requireNonNullElse(summary,""));String safeBody=redactor.redact(Objects.requireNonNullElse(body,""));if(safeSummary.length()>240)throw new IllegalArgumentException("消息摘要超过 240 字符");if(safeBody.length()>maxChars)throw new IllegalArgumentException("消息正文超过大小上限");return CrossProcessFileLock.withLock(paths.lockFile(team,"mailbox"),()->{if(readAll(team,recipient).size()>=maxMessages)throw new TeamException("Mailbox 消息数达到上限");MailboxMessage m=new MailboxMessage(1,UUID.randomUUID().toString(),team,sender,recipient,Objects.requireNonNull(type),safeSummary,safeBody,taskId,clock.instant(),null);log.append(paths.mailboxFile(team,recipient),encodeMessage(m));return m;});}
    public synchronized List<MailboxMessage> broadcast(String team,String sender,Collection<String> recipients,MailboxMessageType type,String summary,String body,String taskId){List<MailboxMessage> result=new ArrayList<>();for(String recipient:new LinkedHashSet<>(recipients))if(!recipient.equals(sender))result.add(send(team,sender,recipient,type,summary,body,taskId));return List.copyOf(result);}
    public synchronized List<MailboxMessage> unread(String team,String recipient){return readAll(team,recipient).stream().filter(m->m.consumedAt()==null).toList();}
    public synchronized boolean acknowledge(String team,String recipient,String messageId){return CrossProcessFileLock.withLock(paths.lockFile(team,"mailbox"),()->{List<MailboxMessage> all=readAll(team,recipient);MailboxMessage target=all.stream().filter(m->m.id().equals(messageId)).findFirst().orElseThrow(()->new TeamException("Mailbox 消息不存在"));if(target.consumedAt()!=null)return false;ObjectNode ack=mapper.createObjectNode();ack.put("record","ack");ack.put("schemaVersion",1);ack.put("messageId",messageId);ack.put("consumedAt",clock.instant().toString());log.append(paths.mailboxFile(team,recipient),ack.toString());return true;});}
    public synchronized List<MailboxMessage> readAll(String team,String recipient){Map<String,MailboxMessage> messages=new LinkedHashMap<>();Map<String,Instant> acks=new HashMap<>();for(String line:log.readRecoveringTail(paths.mailboxFile(team,recipient))){try{JsonNode n=mapper.readTree(line);String record=n.path("record").asText();if("message".equals(record)){MailboxMessage m=decode(n);if(!team.equals(m.teamName())||!recipient.equals(m.recipientAgentId()))throw new TeamException("Mailbox 记录跨团队或收件人不匹配");if(messages.putIfAbsent(m.id(),m)!=null)throw new TeamException("Mailbox 消息 ID 重复");}else if("ack".equals(record)){if(n.path("schemaVersion").asInt()!=1)throw new TeamException("Mailbox ACK 版本无效");String id=text(n,"messageId");Instant consumed=Instant.parse(text(n,"consumedAt"));acks.putIfAbsent(id,consumed);}else throw new TeamException("未知 Mailbox 记录类型");}catch(TeamException e){throw e;}catch(RuntimeException|java.io.IOException e){throw new TeamException("Mailbox 记录损坏",e);}}for(String id:acks.keySet())if(!messages.containsKey(id))throw new TeamException("Mailbox ACK 引用未知消息");return messages.values().stream().map(m->acks.containsKey(m.id())?m.consumed(acks.get(m.id())):m).toList();}
    private String encodeMessage(MailboxMessage m){ObjectNode n=mapper.createObjectNode();n.put("record","message");n.put("schemaVersion",m.schemaVersion());n.put("id",m.id());n.put("teamName",m.teamName());n.put("senderAgentId",m.senderAgentId());n.put("recipientAgentId",m.recipientAgentId());n.put("type",m.type().name());n.put("summary",m.summary());n.put("body",m.body());n.put("taskId",m.taskId());n.put("createdAt",m.createdAt().toString());return n.toString();}
    private static MailboxMessage decode(JsonNode n){if(n.path("schemaVersion").asInt()!=1)throw new TeamException("Mailbox 版本无效");return new MailboxMessage(1,text(n,"id"),text(n,"teamName"),text(n,"senderAgentId"),text(n,"recipientAgentId"),MailboxMessageType.valueOf(text(n,"type")),n.path("summary").asText(""),n.path("body").asText(""),n.path("taskId").asText(""),Instant.parse(text(n,"createdAt")),null);}
    private static String text(JsonNode n,String field){String v=n.path(field).asText("");if(v.isBlank())throw new TeamException("Mailbox 缺少字段: "+field);return v;}
}
